package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"

	"github.com/washanhanzi/holiday-cn-go/pkg/holiday"
)

type Schema struct {
	Schema string           `json:"$schema"`
	ID     string           `json:"$id"`
	Year   int              `json:"year"`
	Papers []string         `json:"papers"`
	Days   []arrangementDay `json:"days"`
}

// arrangementDay mirrors a day entry in the upstream JSON.
type arrangementDay struct {
	Name     string `json:"name"`
	Date     string `json:"date"`
	IsOffDay bool   `json:"isOffDay"`
}

type generatedYear struct {
	Year int
	Days []holiday.Day
}

const yearTmpl = `// Code generated by generator; DO NOT EDIT.
package holiday

// Init{{ .Year }} initializes the holiday data for year {{ .Year }}
func Init{{ .Year }}() map[string]Day {
	data := make(map[string]Day, {{ len .Days }})
	{{- range .Days }}
	data["{{ .Date }}"] = Day{ArrangementYear: {{ .ArrangementYear }}, Name: "{{ .Name }}", Date: "{{ .Date }}", IsOffDay: {{ .IsOffDay }}}
	{{- end }}
	return data
}

// IsHoliday{{ .Year }} checks if a given date in {{ .Year }} is a holiday
func IsHoliday{{ .Year }}(dateStr string) (bool, string, error) {
	data := getYearData({{ .Year }})
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}`

const mainTmpl = `// Code generated by generator; DO NOT EDIT.
package holiday

import (
	"fmt"
	"sync"
	"time"
)

// Day represents a single holiday or workday entry
type Day struct {
	// ArrangementYear is the original JSON arrangement year, which may differ from Date's year.
	ArrangementYear int    ` + "`json:\"arrangementYear\"`" + `
	Name            string ` + "`json:\"name\"`" + `
	Date            string ` + "`json:\"date\"`" + `
	IsOffDay        bool   ` + "`json:\"isOffDay\"`" + `
}

// lazyYearData builds a year's map once and publishes it to all callers.
type lazyYearData struct {
	once sync.Once
	init func() map[string]Day
	data map[string]Day
}

// yearData contains independent initialization state for each supported year.
var yearData = map[int]*lazyYearData{
	{{- range .Years }}
	{{ . }}: {init: Init{{ . }}},
	{{- end }}
}

// GetYearData returns an independent copy of a year's holiday data.
// Modifying the returned map does not affect subsequent holiday checks.
// It returns nil for unsupported years.
func GetYearData(year int) map[string]Day {
	data := getYearData(year)
	if data == nil {
		return nil
	}
	result := make(map[string]Day, len(data))
	for date, day := range data {
		result[date] = day
	}
	return result
}

// CheckHoliday returns a copy of the record for date, using its own timezone.
// It returns (nil, nil) if no record exists, or an error for unsupported years.
func CheckHoliday(date time.Time) (*Day, error) {
	data := getYearData(date.Year())
	if data == nil {
		return nil, fmt.Errorf("no holiday data for year %d", date.Year())
	}
	day, exists := data[date.Format("2006-01-02")]
	if !exists {
		return nil, nil
	}
	return &day, nil
}

// getYearData initializes each year's private, read-only cache once.
func getYearData(year int) map[string]Day {
	entry, ok := yearData[year]
	if !ok {
		return nil
	}
	entry.once.Do(func() {
		entry.data = entry.init()
	})
	return entry.data
}`

func main() {
	if len(os.Args) != 3 {
		fmt.Println("Usage: generator <data-dir> <output-dir>")
		os.Exit(1)
	}
	if err := generate(os.Args[1], os.Args[2]); err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func generate(dataDir, outputDir string) error {
	files, err := os.ReadDir(dataDir)
	if err != nil {
		return fmt.Errorf("read data directory: %w", err)
	}

	// Read each source once for the full build. Each generated map uses only
	// its own arrangement and entries for its dates from the next year.
	yearDays := make(map[int]map[string]holiday.Day)
	var emptyYears []int
	for _, file := range files {
		fileName := file.Name()
		if !strings.HasSuffix(fileName, ".json") ||
			fileName == "schema.json" || fileName == "renovate.json" || file.IsDir() {
			continue
		}
		content, err := os.ReadFile(filepath.Join(dataDir, fileName))
		if err != nil {
			return fmt.Errorf("read %s: %w", fileName, err)
		}
		var schema Schema
		if err := json.Unmarshal(content, &schema); err != nil {
			return fmt.Errorf("decode %s: %w", fileName, err)
		}
		if len(schema.Days) == 0 {
			emptyYears = append(emptyYears, schema.Year)
			continue
		}
		data := make(map[string]holiday.Day, len(schema.Days))
		for _, day := range schema.Days {
			if _, err := time.Parse("2006-01-02", day.Date); err != nil {
				return fmt.Errorf("invalid date in year %d: %w", schema.Year, err)
			}
			data[day.Date] = holiday.Day{
				ArrangementYear: schema.Year,
				Name:            day.Name,
				Date:            day.Date,
				IsOffDay:        day.IsOffDay,
			}
		}
		yearDays[schema.Year] = data
	}

	years := make([]int, 0, len(yearDays))
	for year := range yearDays {
		years = append(years, year)
	}
	sort.Ints(years)
	yearTpl := template.Must(template.New("year").Parse(yearTmpl))
	for _, year := range years {
		// Keep this year's original arrangement entries, including dates outside
		// its calendar year, and import only dates in this year from year+1.
		// For example, 2019's arrangements contain the 2018-12-29 make-up
		// workday, so both generated year APIs will expose that record.
		// The next year's entry wins on overlap. Previous years are ignored;
		// if year+1 is absent, the original records remain unchanged.
		// Merging before compilation lets runtime queries lazily load just
		// the requested year through GetYearData.
		data := yearDays[year]
		datePrefix := fmt.Sprintf("%04d-", year)
		for date, day := range yearDays[year+1] {
			if strings.HasPrefix(date, datePrefix) {
				data[date] = day
			}
		}
		dates := make([]string, 0, len(data))
		for date := range data {
			dates = append(dates, date)
		}
		sort.Strings(dates)
		days := make([]holiday.Day, 0, len(dates))
		for _, date := range dates {
			days = append(days, data[date])
		}
		path := filepath.Join(outputDir, fmt.Sprintf("year_%d.go", year))
		if err := writeGeneratedFile(path, yearTpl, generatedYear{Year: year, Days: days}); err != nil {
			return err
		}
	}
	mainTpl := template.Must(template.New("main").Parse(mainTmpl))
	if err := writeGeneratedFile(filepath.Join(outputDir, "holiday.go"), mainTpl, struct{ Years []int }{years}); err != nil {
		return err
	}
	// An existing generated year must also disappear when its source becomes empty.
	for _, year := range emptyYears {
		path := filepath.Join(outputDir, fmt.Sprintf("year_%d.go", year))
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("remove empty year %s: %w", path, err)
		}
	}
	return nil
}

func writeGeneratedFile(path string, tmpl *template.Template, data interface{}) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create %s: %w", path, err)
	}
	if err := tmpl.Execute(f, data); err != nil {
		f.Close()
		return fmt.Errorf("generate %s: %w", path, err)
	}
	return f.Close()
}
