// Code generated by generator; DO NOT EDIT.
package holiday

import (
	"fmt"
	"sync"
	"time"
)

// Day represents a single holiday or workday entry
type Day struct {
	// ArrangementYear is the original JSON arrangement year, which may differ from Date's year.
	ArrangementYear int    `json:"arrangementYear"`
	Name            string `json:"name"`
	Date            string `json:"date"`
	IsOffDay        bool   `json:"isOffDay"`
}

// lazyYearData builds a year's map once and publishes it to all callers.
type lazyYearData struct {
	once     sync.Once
	mutation sync.Mutex
	mu       sync.RWMutex
	init     func() map[string]Day
	data     map[string]Day
}

// yearData contains independent initialization state for each supported year.
var yearData = map[int]*lazyYearData{
	2007: {init: Init2007},
	2008: {init: Init2008},
	2009: {init: Init2009},
	2010: {init: Init2010},
	2011: {init: Init2011},
	2012: {init: Init2012},
	2013: {init: Init2013},
	2014: {init: Init2014},
	2015: {init: Init2015},
	2016: {init: Init2016},
	2017: {init: Init2017},
	2018: {init: Init2018},
	2019: {init: Init2019},
	2020: {init: Init2020},
	2021: {init: Init2021},
	2022: {init: Init2022},
	2023: {init: Init2023},
	2024: {init: Init2024},
	2025: {init: Init2025},
	2026: {init: Init2026},
}

// GetYearData returns an independent copy of a year's holiday data.
// Modifying the returned map does not affect subsequent holiday checks.
// It returns nil for unsupported years.
func GetYearData(year int) map[string]Day {
	data := getYearData(year)
	if data == nil {
		return nil
	}
	return cloneYearData(data)
}

func cloneYearData(data map[string]Day) map[string]Day {
	result := make(map[string]Day, len(data))
	for date, day := range data {
		result[date] = day
	}
	return result
}

// CheckHoliday returns a copy of the record for date, using its own timezone.
// It returns (nil, nil) if no record exists, or an error for unsupported years.
func CheckHoliday(date time.Time) (*Day, error) {
	data := getYearData(date.Year())
	if data == nil {
		return nil, fmt.Errorf("no holiday data for year %d", date.Year())
	}
	day, exists := data[date.Format("2006-01-02")]
	if !exists {
		return nil, nil
	}
	return &day, nil
}

// MutateDay initializes the date's year and passes a private copy of its record
// to mutate. dateStr must be a valid YYYY-MM-DD calendar date; no timezone
// conversion is performed. Missing records
// start with Date and ArrangementYear set from date, and other fields zeroed.
// Changes are published atomically on return and affect only this year's cache.
// The callback must not change Date or call MutateDay. It may read the cache.
// It must finish writing before returning; retaining the pointer cannot change
// the cache afterward. A panic discards changes and propagates to the caller.
// Invalid dates, unsupported years, nil callbacks, and changes to Date return an error.
func MutateDay(dateStr string, mutate func(*Day)) error {
	date, err := time.Parse("2006-01-02", dateStr)
	if err != nil {
		return fmt.Errorf("invalid date %q: expected YYYY-MM-DD: %w", dateStr, err)
	}
	if date.Format("2006-01-02") != dateStr {
		return fmt.Errorf("invalid date %q: expected YYYY-MM-DD", dateStr)
	}
	year := date.Year()
	entry, ok := yearData[year]
	if !ok {
		return fmt.Errorf("no holiday data for year %d", year)
	}
	if mutate == nil {
		return fmt.Errorf("mutate callback must not be nil")
	}
	entry.mutation.Lock()
	defer entry.mutation.Unlock()

	data := getYearData(year)
	key := dateStr
	day, exists := data[key]
	if !exists {
		day = Day{Date: key, ArrangementYear: year}
	}
	mutate(&day)
	if day.Date != key {
		return fmt.Errorf("mutate callback must not change Date from %s", key)
	}
	updated := cloneYearData(data)
	updated[key] = day
	entry.mu.Lock()
	entry.data = updated
	entry.mu.Unlock()
	return nil
}

// getYearData initializes each year's cache once and returns an immutable snapshot.
func getYearData(year int) map[string]Day {
	entry, ok := yearData[year]
	if !ok {
		return nil
	}
	entry.once.Do(func() {
		entry.data = entry.init()
	})
	entry.mu.RLock()
	defer entry.mu.RUnlock()
	return entry.data
}