// Code generated by generator; DO NOT EDIT.
package holiday

import (
	"fmt"
	"sync"
	"time"
)

// Day represents a single holiday or workday entry
type Day struct {
	// ArrangementYear is the original JSON arrangement year, which may differ from Date's year.
	ArrangementYear int    `json:"arrangementYear"`
	Name            string `json:"name"`
	Date            string `json:"date"`
	IsOffDay        bool   `json:"isOffDay"`
}

// lazyYearData builds a year's map once and publishes it to all callers.
type lazyYearData struct {
	once sync.Once
	init func() map[string]Day
	data map[string]Day
}

// yearData contains independent initialization state for each supported year.
var yearData = map[int]*lazyYearData{
	2007: {init: Init2007},
	2008: {init: Init2008},
	2009: {init: Init2009},
	2010: {init: Init2010},
	2011: {init: Init2011},
	2012: {init: Init2012},
	2013: {init: Init2013},
	2014: {init: Init2014},
	2015: {init: Init2015},
	2016: {init: Init2016},
	2017: {init: Init2017},
	2018: {init: Init2018},
	2019: {init: Init2019},
	2020: {init: Init2020},
	2021: {init: Init2021},
	2022: {init: Init2022},
	2023: {init: Init2023},
	2024: {init: Init2024},
	2025: {init: Init2025},
	2026: {init: Init2026},
}

// GetYearData returns an independent copy of a year's holiday data.
// Modifying the returned map does not affect subsequent holiday checks.
// It returns nil for unsupported years.
func GetYearData(year int) map[string]Day {
	data := getYearData(year)
	if data == nil {
		return nil
	}
	result := make(map[string]Day, len(data))
	for date, day := range data {
		result[date] = day
	}
	return result
}

// CheckHoliday returns a copy of the record for date, using its own timezone.
// It returns (nil, nil) if no record exists, or an error for unsupported years.
func CheckHoliday(date time.Time) (*Day, error) {
	data := getYearData(date.Year())
	if data == nil {
		return nil, fmt.Errorf("no holiday data for year %d", date.Year())
	}
	day, exists := data[date.Format("2006-01-02")]
	if !exists {
		return nil, nil
	}
	return &day, nil
}

// getYearData initializes each year's private, read-only cache once.
func getYearData(year int) map[string]Day {
	entry, ok := yearData[year]
	if !ok {
		return nil
	}
	entry.once.Do(func() {
		entry.data = entry.init()
	})
	return entry.data
}