// Code generated by generator; DO NOT EDIT.
package holiday

// Init2022 initializes the holiday data for year 2022
func Init2022() map[string]Day {
	data := make(map[string]Day, 39)
	data["2022-01-01"] = Day{ArrangementYear: 2022, Name: "元旦", Date: "2022-01-01", IsOffDay: true}
	data["2022-01-02"] = Day{ArrangementYear: 2022, Name: "元旦", Date: "2022-01-02", IsOffDay: true}
	data["2022-01-03"] = Day{ArrangementYear: 2022, Name: "元旦", Date: "2022-01-03", IsOffDay: true}
	data["2022-01-29"] = Day{ArrangementYear: 2022, Name: "春节", Date: "2022-01-29", IsOffDay: false}
	data["2022-01-30"] = Day{ArrangementYear: 2022, Name: "春节", Date: "2022-01-30", IsOffDay: false}
	data["2022-01-31"] = Day{ArrangementYear: 2022, Name: "春节", Date: "2022-01-31", IsOffDay: true}
	data["2022-02-01"] = Day{ArrangementYear: 2022, Name: "春节", Date: "2022-02-01", IsOffDay: true}
	data["2022-02-02"] = Day{ArrangementYear: 2022, Name: "春节", Date: "2022-02-02", IsOffDay: true}
	data["2022-02-03"] = Day{ArrangementYear: 2022, Name: "春节", Date: "2022-02-03", IsOffDay: true}
	data["2022-02-04"] = Day{ArrangementYear: 2022, Name: "春节", Date: "2022-02-04", IsOffDay: true}
	data["2022-02-05"] = Day{ArrangementYear: 2022, Name: "春节", Date: "2022-02-05", IsOffDay: true}
	data["2022-02-06"] = Day{ArrangementYear: 2022, Name: "春节", Date: "2022-02-06", IsOffDay: true}
	data["2022-04-02"] = Day{ArrangementYear: 2022, Name: "清明节", Date: "2022-04-02", IsOffDay: false}
	data["2022-04-03"] = Day{ArrangementYear: 2022, Name: "清明节", Date: "2022-04-03", IsOffDay: true}
	data["2022-04-04"] = Day{ArrangementYear: 2022, Name: "清明节", Date: "2022-04-04", IsOffDay: true}
	data["2022-04-05"] = Day{ArrangementYear: 2022, Name: "清明节", Date: "2022-04-05", IsOffDay: true}
	data["2022-04-24"] = Day{ArrangementYear: 2022, Name: "劳动节", Date: "2022-04-24", IsOffDay: false}
	data["2022-04-30"] = Day{ArrangementYear: 2022, Name: "劳动节", Date: "2022-04-30", IsOffDay: true}
	data["2022-05-01"] = Day{ArrangementYear: 2022, Name: "劳动节", Date: "2022-05-01", IsOffDay: true}
	data["2022-05-02"] = Day{ArrangementYear: 2022, Name: "劳动节", Date: "2022-05-02", IsOffDay: true}
	data["2022-05-03"] = Day{ArrangementYear: 2022, Name: "劳动节", Date: "2022-05-03", IsOffDay: true}
	data["2022-05-04"] = Day{ArrangementYear: 2022, Name: "劳动节", Date: "2022-05-04", IsOffDay: true}
	data["2022-05-07"] = Day{ArrangementYear: 2022, Name: "劳动节", Date: "2022-05-07", IsOffDay: false}
	data["2022-06-03"] = Day{ArrangementYear: 2022, Name: "端午节", Date: "2022-06-03", IsOffDay: true}
	data["2022-06-04"] = Day{ArrangementYear: 2022, Name: "端午节", Date: "2022-06-04", IsOffDay: true}
	data["2022-06-05"] = Day{ArrangementYear: 2022, Name: "端午节", Date: "2022-06-05", IsOffDay: true}
	data["2022-09-10"] = Day{ArrangementYear: 2022, Name: "中秋节", Date: "2022-09-10", IsOffDay: true}
	data["2022-09-11"] = Day{ArrangementYear: 2022, Name: "中秋节", Date: "2022-09-11", IsOffDay: true}
	data["2022-09-12"] = Day{ArrangementYear: 2022, Name: "中秋节", Date: "2022-09-12", IsOffDay: true}
	data["2022-10-01"] = Day{ArrangementYear: 2022, Name: "国庆节", Date: "2022-10-01", IsOffDay: true}
	data["2022-10-02"] = Day{ArrangementYear: 2022, Name: "国庆节", Date: "2022-10-02", IsOffDay: true}
	data["2022-10-03"] = Day{ArrangementYear: 2022, Name: "国庆节", Date: "2022-10-03", IsOffDay: true}
	data["2022-10-04"] = Day{ArrangementYear: 2022, Name: "国庆节", Date: "2022-10-04", IsOffDay: true}
	data["2022-10-05"] = Day{ArrangementYear: 2022, Name: "国庆节", Date: "2022-10-05", IsOffDay: true}
	data["2022-10-06"] = Day{ArrangementYear: 2022, Name: "国庆节", Date: "2022-10-06", IsOffDay: true}
	data["2022-10-07"] = Day{ArrangementYear: 2022, Name: "国庆节", Date: "2022-10-07", IsOffDay: true}
	data["2022-10-08"] = Day{ArrangementYear: 2022, Name: "国庆节", Date: "2022-10-08", IsOffDay: false}
	data["2022-10-09"] = Day{ArrangementYear: 2022, Name: "国庆节", Date: "2022-10-09", IsOffDay: false}
	data["2022-12-31"] = Day{ArrangementYear: 2023, Name: "元旦", Date: "2022-12-31", IsOffDay: true}
	return data
}

// IsHoliday2022 checks if a given date in 2022 is a holiday
func IsHoliday2022(dateStr string) (bool, string, error) {
	data := getYearData(2022)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}