// Code generated by generator; DO NOT EDIT.
package holiday

// Year2013Data contains holiday data for year 2013
var Year2013Data map[string]Day

// Init2013 initializes the holiday data for year 2013
func Init2013() map[string]Day {
	data := make(map[string]Day, 41)
	data["2013-01-01"] = Day{ArrangementYear: 2013, Name: "元旦", Date: "2013-01-01", IsOffDay: true}
	data["2013-01-02"] = Day{ArrangementYear: 2013, Name: "元旦", Date: "2013-01-02", IsOffDay: true}
	data["2013-01-03"] = Day{ArrangementYear: 2013, Name: "元旦", Date: "2013-01-03", IsOffDay: true}
	data["2013-01-05"] = Day{ArrangementYear: 2013, Name: "元旦", Date: "2013-01-05", IsOffDay: false}
	data["2013-01-06"] = Day{ArrangementYear: 2013, Name: "元旦", Date: "2013-01-06", IsOffDay: false}
	data["2013-02-09"] = Day{ArrangementYear: 2013, Name: "春节", Date: "2013-02-09", IsOffDay: true}
	data["2013-02-10"] = Day{ArrangementYear: 2013, Name: "春节", Date: "2013-02-10", IsOffDay: true}
	data["2013-02-11"] = Day{ArrangementYear: 2013, Name: "春节", Date: "2013-02-11", IsOffDay: true}
	data["2013-02-12"] = Day{ArrangementYear: 2013, Name: "春节", Date: "2013-02-12", IsOffDay: true}
	data["2013-02-13"] = Day{ArrangementYear: 2013, Name: "春节", Date: "2013-02-13", IsOffDay: true}
	data["2013-02-14"] = Day{ArrangementYear: 2013, Name: "春节", Date: "2013-02-14", IsOffDay: true}
	data["2013-02-15"] = Day{ArrangementYear: 2013, Name: "春节", Date: "2013-02-15", IsOffDay: true}
	data["2013-02-16"] = Day{ArrangementYear: 2013, Name: "春节", Date: "2013-02-16", IsOffDay: false}
	data["2013-02-17"] = Day{ArrangementYear: 2013, Name: "春节", Date: "2013-02-17", IsOffDay: false}
	data["2013-04-04"] = Day{ArrangementYear: 2013, Name: "清明节", Date: "2013-04-04", IsOffDay: true}
	data["2013-04-05"] = Day{ArrangementYear: 2013, Name: "清明节", Date: "2013-04-05", IsOffDay: true}
	data["2013-04-06"] = Day{ArrangementYear: 2013, Name: "清明节", Date: "2013-04-06", IsOffDay: true}
	data["2013-04-07"] = Day{ArrangementYear: 2013, Name: "清明节", Date: "2013-04-07", IsOffDay: false}
	data["2013-04-27"] = Day{ArrangementYear: 2013, Name: "劳动节", Date: "2013-04-27", IsOffDay: false}
	data["2013-04-28"] = Day{ArrangementYear: 2013, Name: "劳动节", Date: "2013-04-28", IsOffDay: false}
	data["2013-04-29"] = Day{ArrangementYear: 2013, Name: "劳动节", Date: "2013-04-29", IsOffDay: true}
	data["2013-04-30"] = Day{ArrangementYear: 2013, Name: "劳动节", Date: "2013-04-30", IsOffDay: true}
	data["2013-05-01"] = Day{ArrangementYear: 2013, Name: "劳动节", Date: "2013-05-01", IsOffDay: true}
	data["2013-06-08"] = Day{ArrangementYear: 2013, Name: "端午节", Date: "2013-06-08", IsOffDay: false}
	data["2013-06-09"] = Day{ArrangementYear: 2013, Name: "端午节", Date: "2013-06-09", IsOffDay: false}
	data["2013-06-10"] = Day{ArrangementYear: 2013, Name: "端午节", Date: "2013-06-10", IsOffDay: true}
	data["2013-06-11"] = Day{ArrangementYear: 2013, Name: "端午节", Date: "2013-06-11", IsOffDay: true}
	data["2013-06-12"] = Day{ArrangementYear: 2013, Name: "端午节", Date: "2013-06-12", IsOffDay: true}
	data["2013-09-19"] = Day{ArrangementYear: 2013, Name: "中秋节", Date: "2013-09-19", IsOffDay: true}
	data["2013-09-20"] = Day{ArrangementYear: 2013, Name: "中秋节", Date: "2013-09-20", IsOffDay: true}
	data["2013-09-21"] = Day{ArrangementYear: 2013, Name: "中秋节", Date: "2013-09-21", IsOffDay: true}
	data["2013-09-22"] = Day{ArrangementYear: 2013, Name: "中秋节", Date: "2013-09-22", IsOffDay: false}
	data["2013-09-29"] = Day{ArrangementYear: 2013, Name: "国庆节", Date: "2013-09-29", IsOffDay: false}
	data["2013-10-01"] = Day{ArrangementYear: 2013, Name: "国庆节", Date: "2013-10-01", IsOffDay: true}
	data["2013-10-02"] = Day{ArrangementYear: 2013, Name: "国庆节", Date: "2013-10-02", IsOffDay: true}
	data["2013-10-03"] = Day{ArrangementYear: 2013, Name: "国庆节", Date: "2013-10-03", IsOffDay: true}
	data["2013-10-04"] = Day{ArrangementYear: 2013, Name: "国庆节", Date: "2013-10-04", IsOffDay: true}
	data["2013-10-05"] = Day{ArrangementYear: 2013, Name: "国庆节", Date: "2013-10-05", IsOffDay: true}
	data["2013-10-06"] = Day{ArrangementYear: 2013, Name: "国庆节", Date: "2013-10-06", IsOffDay: true}
	data["2013-10-07"] = Day{ArrangementYear: 2013, Name: "国庆节", Date: "2013-10-07", IsOffDay: true}
	data["2013-10-12"] = Day{ArrangementYear: 2013, Name: "国庆节", Date: "2013-10-12", IsOffDay: false}
	return data
}

// IsHoliday2013 checks if a given date in 2013 is a holiday
func IsHoliday2013(dateStr string) (bool, string, error) {
	data := getYearData(2013)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}