// Code generated by generator; DO NOT EDIT.
package holiday

// Year2026Data contains holiday data for year 2026
var Year2026Data map[string]Day

// Init2026 initializes the holiday data for year 2026
func Init2026() map[string]Day {
	data := make(map[string]Day, 0)
	return data
}

// IsHoliday2026 checks if a given date in 2026 is a holiday
func IsHoliday2026(dateStr string) (bool, string, error) {
	data := GetYearData(2026)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}