// Code generated by generator; DO NOT EDIT.
package holiday

// Init2008 initializes the holiday data for year 2008
func Init2008() map[string]Day {
	data := make(map[string]Day, 35)
	data["2007-12-29"] = Day{ArrangementYear: 2008, Name: "元旦", Date: "2007-12-29", IsOffDay: false}
	data["2007-12-30"] = Day{ArrangementYear: 2008, Name: "元旦", Date: "2007-12-30", IsOffDay: true}
	data["2007-12-31"] = Day{ArrangementYear: 2008, Name: "元旦", Date: "2007-12-31", IsOffDay: true}
	data["2008-01-01"] = Day{ArrangementYear: 2008, Name: "元旦", Date: "2008-01-01", IsOffDay: true}
	data["2008-02-02"] = Day{ArrangementYear: 2008, Name: "春节", Date: "2008-02-02", IsOffDay: false}
	data["2008-02-03"] = Day{ArrangementYear: 2008, Name: "春节", Date: "2008-02-03", IsOffDay: false}
	data["2008-02-06"] = Day{ArrangementYear: 2008, Name: "春节", Date: "2008-02-06", IsOffDay: true}
	data["2008-02-07"] = Day{ArrangementYear: 2008, Name: "春节", Date: "2008-02-07", IsOffDay: true}
	data["2008-02-08"] = Day{ArrangementYear: 2008, Name: "春节", Date: "2008-02-08", IsOffDay: true}
	data["2008-02-09"] = Day{ArrangementYear: 2008, Name: "春节", Date: "2008-02-09", IsOffDay: true}
	data["2008-02-10"] = Day{ArrangementYear: 2008, Name: "春节", Date: "2008-02-10", IsOffDay: true}
	data["2008-02-11"] = Day{ArrangementYear: 2008, Name: "春节", Date: "2008-02-11", IsOffDay: true}
	data["2008-02-12"] = Day{ArrangementYear: 2008, Name: "春节", Date: "2008-02-12", IsOffDay: true}
	data["2008-04-04"] = Day{ArrangementYear: 2008, Name: "清明节", Date: "2008-04-04", IsOffDay: true}
	data["2008-04-05"] = Day{ArrangementYear: 2008, Name: "清明节", Date: "2008-04-05", IsOffDay: true}
	data["2008-04-06"] = Day{ArrangementYear: 2008, Name: "清明节", Date: "2008-04-06", IsOffDay: true}
	data["2008-05-01"] = Day{ArrangementYear: 2008, Name: "“五一”国际劳动节", Date: "2008-05-01", IsOffDay: true}
	data["2008-05-02"] = Day{ArrangementYear: 2008, Name: "“五一”国际劳动节", Date: "2008-05-02", IsOffDay: true}
	data["2008-05-03"] = Day{ArrangementYear: 2008, Name: "“五一”国际劳动节", Date: "2008-05-03", IsOffDay: true}
	data["2008-05-04"] = Day{ArrangementYear: 2008, Name: "“五一”国际劳动节", Date: "2008-05-04", IsOffDay: false}
	data["2008-06-07"] = Day{ArrangementYear: 2008, Name: "端午节", Date: "2008-06-07", IsOffDay: true}
	data["2008-06-08"] = Day{ArrangementYear: 2008, Name: "端午节", Date: "2008-06-08", IsOffDay: true}
	data["2008-06-09"] = Day{ArrangementYear: 2008, Name: "端午节", Date: "2008-06-09", IsOffDay: true}
	data["2008-09-13"] = Day{ArrangementYear: 2008, Name: "中秋节", Date: "2008-09-13", IsOffDay: true}
	data["2008-09-14"] = Day{ArrangementYear: 2008, Name: "中秋节", Date: "2008-09-14", IsOffDay: true}
	data["2008-09-15"] = Day{ArrangementYear: 2008, Name: "中秋节", Date: "2008-09-15", IsOffDay: true}
	data["2008-09-27"] = Day{ArrangementYear: 2008, Name: "国庆节", Date: "2008-09-27", IsOffDay: false}
	data["2008-09-28"] = Day{ArrangementYear: 2008, Name: "国庆节", Date: "2008-09-28", IsOffDay: false}
	data["2008-09-29"] = Day{ArrangementYear: 2008, Name: "国庆节", Date: "2008-09-29", IsOffDay: true}
	data["2008-09-30"] = Day{ArrangementYear: 2008, Name: "国庆节", Date: "2008-09-30", IsOffDay: true}
	data["2008-10-01"] = Day{ArrangementYear: 2008, Name: "国庆节", Date: "2008-10-01", IsOffDay: true}
	data["2008-10-02"] = Day{ArrangementYear: 2008, Name: "国庆节", Date: "2008-10-02", IsOffDay: true}
	data["2008-10-03"] = Day{ArrangementYear: 2008, Name: "国庆节", Date: "2008-10-03", IsOffDay: true}
	data["2008-10-04"] = Day{ArrangementYear: 2008, Name: "国庆节", Date: "2008-10-04", IsOffDay: true}
	data["2008-10-05"] = Day{ArrangementYear: 2008, Name: "国庆节", Date: "2008-10-05", IsOffDay: true}
	return data
}

// IsHoliday2008 checks if a given date in 2008 is a holiday
func IsHoliday2008(dateStr string) (bool, string, error) {
	data := getYearData(2008)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}